/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracaoRouteImport } from './routes/configuracao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as UsuariosNovoRouteImport } from './routes/usuarios_.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoRoute = ConfiguracaoRouteImport.update({
  id: '/configuracao',
  path: '/configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosNovoRoute = UsuariosNovoRouteImport.update({
  id: '/usuarios_/novo',
  path: '/usuarios/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
  '/usuarios_/novo': typeof UsuariosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracao'
    | '/dashboard'
    | '/login'
    | '/usuarios'
    | '/usuarios/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracao'
    | '/dashboard'
    | '/login'
    | '/usuarios'
    | '/usuarios/novo'
  id:
    | '__root__'
    | '/'
    | '/configuracao'
    | '/dashboard'
    | '/login'
    | '/usuarios'
    | '/usuarios_/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracaoRoute: typeof ConfiguracaoRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
  UsuariosNovoRoute: typeof UsuariosNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao': {
      id: '/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof ConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios_/novo': {
      id: '/usuarios_/novo'
      path: '/usuarios/novo'
      fullPath: '/usuarios/novo'
      preLoaderRoute: typeof UsuariosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracaoRoute: ConfiguracaoRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
  UsuariosNovoRoute: UsuariosNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
